export const LangArray =  [ "DCPB Platform - Start the Low - Risk, High - Reward DDMM Staking Program with 1 %Daily Interest Distribution!",
"DCPB平台——开启低⻛险、⾼回报的DDMM质押计划, 每天1 % 利息分成! ",
"Hello there! The DCPB platform takes great pride in its experienced market makers who have achieved considerable profits through market - making transactions on decentralized exchanges(DEX) and centralized exchanges(CEX).We have now developed a low - risk, highyield DDMM staking program for everyone to participate in, where users involved will enjoy a 1 % daily interest distribution.",
"您好! DCPB平台引以为傲的做市商拥有丰富的经验, 在去中⼼化交易所 (DEX) 和中⼼化 交易所 (CEX) 的做市交易中取得了可观的盈利。现在, 我们为任何⼈开发了⼀项低分险、 ⾼收益的DDMM质押计划, 并且参与其中的⽤户将享受每天1 % 的利息分成。",
"As a participant, you can secure stable returns by staking your funds in the DDMM program.We understand the importance of risk control, and thus, we are committed to providing you with the lowest possible risk level while ensuring substantial returns.Meanwhile, to foster community development and growth, DCPB has minted 3 million shareholder equity NFTs as rewards for individuals activelyengaged in community building and promotion.These unique and valuable digital assets will bring additional benefits and privileges to their holders.",
"作为参与者, 您可以通过将资⾦质押到DDMM计划中获得稳定的回报。我们深知⻛险控制 的重要性, 因此我们致⼒于为您提供最低的⻛险⽔平, 同时确保您能够获得可观的收益。 与此同时, 为了扩⼤社区建设和发展, DCPB还特别铸造了300万枚股东权益NFT, 作为奖 励赠送给积极参与社区建设和推⼴的⼈⼠。这将是⼀种独特⽽有价值的数字资产, 将为持有 者带来额外的福利和特权。",
"Additionally, DCPB is actively promoting the adoption of cryptocurrency payments worldwide and planning to develop its own public blockchain.This initiative will create extensive use cases and provide users with more opportunities to participate in and benefit from the development of blockchain technology.To support the operation and transactions on the public blockchain, we will also introduce DC Coin as a form of fuel consumption.As the application scenarios for DCPB's public chain expand, the value of DC Coin is expected to rise.",
"此外, DCPB正积极推动全球加密货币⽀付的落地, 并计划开发⾃⼰的公链。这⼀举措将带 来⼴泛的应⽤场景, 为⽤户提供更多机会参与和受益于区块链技术的发展。为了⽀撑公链的 运营和交易, 我们还将推出DC币作为燃料消耗的⼀种形式。随着DCPB公链应⽤场景的扩 ⼤, DC币的价值也将⽔涨船⾼。",
"Finally, it's worth emphasizing that holders of DCPB shareholder equity NFTs will be the greatest beneficiaries.In the early stages, DC Coin will only be released to those who possess the NFTs, providing holders with unique advantages and more opportunities.Therefore, join the DCPB platform, participate in our DDMM staking program, and enjoy a 1 % daily interest distribution.Also, actively engage in community building to have a chance of acquiring the valuable shareholder equity NFTs and become the prime beneficiaries in DCPB's future development.",
"最后, 我们要强调的是, 持有DCPB股东权益NFT的⼈将是最⼤的受益者。因为在初期阶 段, DC币将仅向持有NFT的⼈释放。这将为持有者带来独特的优势和更多机会。所以, 加 ⼊DCPB平台, 参与我们的DDMM质押计划, 享受每天1 % 的利息分成。同时, 积极参与社 区建设, 有机会获得珍贵的股东权益NFT, 成为DCPB未来发展中的最⼤受益者。",
"Let's stride towards the future and create a broader cryptocurrency world!",
"⼀起迈向未来, 开创更⼴阔的加密货币世界! ",
"USDT Staking",
"USDT资押",
"Allowance Amount",
"允许⾦额",
"! You'll need to first create allowance of required amount before staking.",
"您必须设置允许的质押⾦额",
"Allowance",
"允许的",
"Create Allowance",
"同意",
"Staking Amount",
"质押数量",
"Available",
"可⽤的",
"Staking Amount limit",
"质押数量限制",
"Min Staking Amount",
"最低质押数量",
"Max Staking Amount",
"最⼤质押数量",
"Unlimited",
"⽆限制",
"Daily Reward",
"⽇化奖励",
"I have read and agreed to the DDMM staking Service Agreement, investing in the cryptocurrency market fluctuates grealty, and participants must self - assess thier risks and carefully choose the amount of investment.",
"本⼈已阅读并同意《DDMM质押服务协议》, 投资加密货币市场波动较⼤, 参与者需⾃⾏ 评估⻛险, 慎重选择投资⾦额。",
"Confirm",
"确认",
"Staking List",
"质押清单",
"Staking Date:",
"资押⽇期: ",
"Staking Amount:",
"质押数量: ",
"Reward Value:",
"奖励值: ",
"Booster Value:",
"加速值: ",
"Total Profit Value: ",
"利润总值",
"Max",
"全部",
"Wallet",
"钱包",
"Reward Value",
"奖励值",
"max",
"全部",
"Available",
"可⽤的",
"Booster Value",
"加速值",
"Total Claimed Reward Value",
"奖励值提现总额",
"Total Claimed Booster Value",
"加速值提现总额",
"Exchange",
"兑换",
"Confirm",
"确认",
"Community",
"社区",
"Rank Status",
"级别状态",
"Claim NFT",
"领取NFT",
"Claim DC ",
"领取DC币",
"NFT Reward:",
"NFT奖励: ",
"NFT Staking:",
"NFT质押: ",
"Staking Reward:",
"质押奖励: ",
"DC Coin Sell:",
"DC币售出: ",
"DC Coin Profit: ",
"DC币盈利",
"NFT Staking",
"NFT质押",
"Available:",
"可⽤的",
"Sign In",
"登入",
"Referral's ID(Optional)",
"推荐人ID (必须）",
"You have already staked",
"您已经资押",
"You wont be able to stake again, until the current stake is over. ",
"您必须等到上限余额剩下百分之二十，才可以进行新资押。",
"View Stakes",
"查看资押",
"Available",
"可⽤的",
"Stake NFT",
"质押NFT",
"Min",
"最低",
"Intrest Value",
"奖励值"
]